### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yidunsanwanfan** [theComputeKid/ehl-point-stationary#1]
Hello, in your script file A, why is the definition of hr missing density? Are you assuming liquids are incompressible?

**Comment by theComputeKid** [comment]
Yes, that is correct.

**Comment by yidunsanwanfan** [comment]
Thank you for responding to my message. I later found in Venner's book that he also assumes that the fluid is incompressible, which I didn't notice before.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月24日(星期天) 晚上6:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [theComputeKid/ehl-point-stationary] question (Issue #1)





 
Yes, that is correct.
